//GET ALL
GET http://localhost:3000/orders

###
//GET ONE
GET http://localhost:3000/orders/dlmax9Av

###
//CREATE
POST http://localhost:3000/orders
Content-Type: application/json

{
    "name": "My product"
}

###
//UPDATE ORDER DELIVERED
PATCH http://localhost:3000/orders/dlmax9Av